language: java
jdk:
 - oraclejdk8
sudo: required
before_install:
 - curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
 - sudo apt-get install -y nodejs
 - npm install -g npm@2
 - npm install
 - npm install -g bower
 - npm install -g grunt-cli grunt
 - bower install
install: true
script:
 - grunt build
 - ./gradlew webjar
